name: Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/environments/dev/**'

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_aws_region: ap-northeast-2
  TF_VAR_project_name: focus-tracking-platform
  TF_VAR_environment: dev
  TF_VAR_stack_name: main
  TF_VAR_vpc_cidr: 10.0.0.0/16
  TF_VAR_az_a: ap-northeast-2a
  TF_VAR_az_c: ap-northeast-2c
  TF_VAR_public_subnet_a_cidr: 10.0.1.0/24
  TF_VAR_public_subnet_c_cidr: 10.0.2.0/24
  TF_VAR_private_app_subnet_a_cidr: 10.0.11.0/24
  TF_VAR_private_app_subnet_c_cidr: 10.0.12.0/24
  TF_VAR_private_db_subnet_a_cidr: 10.0.21.0/24
  TF_VAR_private_db_subnet_c_cidr: 10.0.22.0/24

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS 인증 (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Terraform 설치
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve